import NavBar from "./components/NavBar";
import ProfilePic from "./components/ProfilePic";
import "./globals.css";

export const metadata = {
  title: "Dennis &apos; blog",
  description: "Generated by coffee and Zen pouches",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <NavBar />
        <ProfilePic />
        {children}
      </body>
    </html>
  );
}
